export const synthesisPuzzles = [
  {
    id: "propene-to-propylene-oxide",
    title: "Propene to propylene oxide",
    tier: "Core alkenes",
    source: "OpenStax 8.7 / 18.4",
    startName: "Propene",
    startSmiles: "CC=C",
    targetName: "Propylene oxide",
    targetSmiles: "CC1CO1",
    maxSteps: 1,
    allowedReagents: ["mCPBA"],
  },
  {
    id: "propene-to-propylene-glycol",
    title: "Propene to propylene glycol",
    tier: "Core alkenes",
    source: "OpenStax 8.7",
    startName: "Propene",
    startSmiles: "CC=C",
    targetName: "Propylene glycol",
    targetSmiles: "CC(O)CO",
    maxSteps: 1,
    allowedReagents: ["OsO4", "cold KMnO4"],
  },
  {
    id: "propene-to-bromohydrin",
    title: "Propene to bromohydrin",
    tier: "Epoxide follow-on",
    source: "OpenStax 18.5",
    startName: "Propene",
    startSmiles: "CC=C",
    targetName: "1-bromopropan-2-ol",
    targetSmiles: "CC(Br)CO",
    maxSteps: 2,
    allowedReagents: ["mCPBA", "HBr"],
  },
  {
    id: "butyne-to-butanone",
    title: "1-Butyne to 2-butanone",
    tier: "Alkynes",
    source: "OpenStax 9.9",
    startName: "1-Butyne",
    startSmiles: "CCC#C",
    targetName: "2-Butanone",
    targetSmiles: "CCC(=O)C",
    maxSteps: 1,
    allowedReagents: ["HgSO4, H2SO4, H2O"],
  },
  {
    id: "butyne-to-butanal",
    title: "1-Butyne to butanal",
    tier: "Alkynes",
    source: "OpenStax 9.9",
    startName: "1-Butyne",
    startSmiles: "CCC#C",
    targetName: "Butanal",
    targetSmiles: "CCCC=O",
    maxSteps: 1,
    allowedReagents: ["1. R2BH  2. H2O2, NaOH"],
  },
  {
    id: "butyne-chain-extension",
    title: "1-Butyne to 3-hexyne",
    tier: "C-C bond formation",
    source: "OpenStax 9.9",
    startName: "1-Butyne",
    startSmiles: "CCC#C",
    targetName: "3-Hexyne",
    targetSmiles: "CCC#CCC",
    maxSteps: 2,
    allowedReagents: ["NaNH2", "ethyl bromide"],
  },
  {
    id: "butyne-to-hexane",
    title: "1-Butyne to hexane",
    tier: "C-C bond formation",
    source: "OpenStax 9.9",
    startName: "1-Butyne",
    startSmiles: "CCC#C",
    targetName: "Hexane",
    targetSmiles: "CCCCCC",
    maxSteps: 3,
    allowedReagents: ["NaNH2", "ethyl bromide", "H2, Pd/C"],
  },
  {
    id: "butyne-to-trans-3-hexene",
    title: "1-Butyne to trans-3-hexene",
    tier: "C-C bond formation",
    source: "OpenStax 9.9",
    startName: "1-Butyne",
    startSmiles: "CCC#C",
    targetName: "trans-3-Hexene",
    targetSmiles: "CC/C=C/CC",
    maxSteps: 3,
    allowedReagents: ["NaNH2", "ethyl bromide", "Na, NH3"],
  },
  {
    id: "butyne-to-cis-3-hexene",
    title: "1-Butyne to cis-3-hexene",
    tier: "C-C bond formation",
    source: "OpenStax 9.9",
    startName: "1-Butyne",
    startSmiles: "CCC#C",
    targetName: "cis-3-Hexene",
    targetSmiles: "CC/C=C\\CC",
    maxSteps: 3,
    allowedReagents: ["NaNH2", "ethyl bromide", "H2, Lindlar"],
  },
  {
    id: "acetylene-to-2-butanone",
    title: "Acetylene to 2-butanone",
    tier: "Longer alkyne route",
    source: "OpenStax 9.9",
    startName: "Acetylene",
    startSmiles: "C#C",
    targetName: "2-Butanone",
    targetSmiles: "CCC(=O)C",
    maxSteps: 4,
    allowedReagents: ["NaNH2", "ethyl bromide", "HgSO4, H2SO4, H2O"],
  },
  {
    id: "acetylene-to-butanal",
    title: "Acetylene to butanal",
    tier: "Longer alkyne route",
    source: "OpenStax 9.9",
    startName: "Acetylene",
    startSmiles: "C#C",
    targetName: "Butanal",
    targetSmiles: "CCCC=O",
    maxSteps: 4,
    allowedReagents: ["NaNH2", "ethyl bromide", "1. R2BH  2. H2O2, NaOH"],
  },
  {
    id: "propene-to-diol-via-epoxide",
    title: "Propene to propylene glycol via epoxide",
    tier: "Epoxide follow-on",
    source: "OpenStax 18.5",
    startName: "Propene",
    startSmiles: "CC=C",
    targetName: "Propylene glycol",
    targetSmiles: "CC(O)CO",
    maxSteps: 2,
    allowedReagents: ["mCPBA", "H3O+"],
  },
  {
    id: "acetaldehyde-to-2-propanol",
    title: "Acetaldehyde to 2-propanol",
    tier: "Carbonyls",
    source: "OpenStax carbonyl chemistry",
    startName: "Acetaldehyde",
    startSmiles: "CC=O",
    targetName: "2-Propanol",
    targetSmiles: "CC(O)(C)",
    maxSteps: 1,
    allowedReagents: ["CH3MgBr, H3O+"],
  },
  {
    id: "co2-to-benzoic-acid",
    title: "CO2 to benzoic acid",
    tier: "Carbonyls",
    source: "OpenStax carbonyl chemistry",
    startName: "Carbon dioxide",
    startSmiles: "O=C=O",
    targetName: "Benzoic acid",
    targetSmiles: "c1ccccc1C(=O)O",
    maxSteps: 1,
    allowedReagents: ["PhMgBr, H3O+"],
  },
];
